### ISSUE TITLE
two outlet ports at same height make gui crash when trying to connect port

### ISSUE THREAD

**Issue by jschmidl** [SPF-OST/pytrnsys_gui#294]
Error: Traceback (most recent call last):
  File "c:\git\pytrnsys_gui\trnsysGUI\diagram\scene.py", line 27, in mouseMoveEvent
    self.parent().sceneMouseMoveEvent(mouseEvent)
  File "c:\git\pytrnsys_gui\trnsysGUI\diagram\Editor.py", line 401, in sceneMouseMoveEvent
    hitPortItem = self._getHitPortItemOrNone(event)
  File "c:\git\pytrnsys_gui\trnsysGUI\diagram\Editor.py", line 436, in _getHitPortItemOrNone
    raise NotImplementedError("Can't deal with overlapping port items.")
NotImplementedError: Can't deal with overlapping port items.

**Comment by zuckerruebe** [comment]
It doesn't crash any more. However, it's still not possible to connect in that case. Can I close this issue, @jschmidl?

**Comment by jschmidl** [comment]
for me that's fine, maybe we could have a new issue for this functionality, though i don't need this urgently.
